#!/bin/bash

echo "GIT STATUS"
git status -suno
read -p "Continue (Y/n)" yn
echo $yn
if [ "$yn" != "" -a "$yn" != y -a "$yn" != Y ]; then
  echo ABORT
  exit 1
fi
echo

echo "GIT COMMIT ALL"
git commit --all -m cont
echo

echo "GIT PUSH"
git push
echo

echo "GIT STATUS"
git status -suno
